//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-5 l: fllxf
        ///4-5 r: rrrjmrrrrrrh
        ///1-4 k: kkksk
        ///7-8 k: tknsqknzkckrwkjkk
        ///2-3 p: mpbstpxmsxmpnhbwlb
        ///2-7 j: xkjjtjjjj
        ///2-7 m: gczbmgk
        ///15-16 q: qqqqqqqqqckqqqfqqq
        ///7-14 d: dgdddlddddddrvfddnsd
        ///7-12 r: rrrrrrrrbrrrl
        ///2-11 p: zppjpwpqppbnppd
        ///6-8 w: wqhwwnpwwwr
        ///4-10 m: fmkmrrrdkmr
        ///1-2 n: nnjvtnzk
        ///3-8 t: tdxmzslxtvft
        ///13-14 m: mmmmmhmmmmmmmm
        ///9-10 l: lljllllllll
        ///12-16 t: vdtbdtxtttttrctttkt
        ///2-6 q: nqghxqgjqvzswbxww
        ///4-6 k: khkkkkvrkgfwvbd
        ///4-5 r: hrrpv
        ///5-8 g: gggggggg
        ///5-8 f: fjsfftfs
        ///9-12 p: ppfpnxpv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Input {
            get {
                return ResourceManager.GetString("Day02Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......##....#...#..#.#....#....
        ///.......#...#..#..#....##.......
        ///#.#...#........###.#.##..#.....
        ///.......#.....##.#..##...##.##..
        ///.#...#.#...##..........#..#....
        ///#.......##.....###.#...#......#
        ///.........#....#.#.......#..#...
        ///..#.......####.......###..##...
        ///.#.#.##..#.#...##..#...###...##
        ///...................#...........
        ///....#.#.......#..........#.#..#
        ///..#.#...........####.#.......#.
        ///.....#.##..#..##..#.#...#......
        ///#.##...###..#................##
        ///...#...#...#..##.#............#
        ///#.##....##....#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Input {
            get {
                return ResourceManager.GetString("Day03Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:2033
        ///hgt:177cm pid:173cm
        ///ecl:utc byr:2029 hcl:#efcc98 iyr:2023
        ///
        ///pid:337605855 cid:249 byr:1952 hgt:155cm
        ///ecl:grn iyr:2017 eyr:2026 hcl:#866857
        ///
        ///cid:242 iyr:2011 pid:953198122 eyr:2029 ecl:blu hcl:#888785
        ///
        ///hgt:173cm hcl:#341e13
        ///cid:341
        ///pid:112086592
        ///iyr:2012 byr:2011 ecl:amb
        ///eyr:2030
        ///
        ///pid:790332032
        ///iyr:2019
        ///eyr:2023 byr:1969 ecl:brn
        ///hgt:163cm
        ///hcl:#623a2f
        ///
        ///byr:1920 eyr:2023 cid:146 pid:890112986 hgt:171cm hcl:#b6652a iyr:2017 ecl:hzl
        ///
        ///hcl:#c0946f byr:1967 cid:199 ecl:gry
        ///iyr:2012 p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Input {
            get {
                return ResourceManager.GetString("Day04Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFFFBFBLLR
        ///BFBFFBBLLR
        ///BBFFFFBLRR
        ///FBFBFFFRLL
        ///BFFBFFFRRR
        ///BFBFBFFRLR
        ///FFFBBBBLRL
        ///BFFFFBFLLL
        ///FFFFBBFLLR
        ///BBFFBFFRRR
        ///FBBFBBFLRL
        ///BFBFFBFLRR
        ///FBFFBFFLLL
        ///FFFBFFFRLR
        ///FFFBFBBLLR
        ///BBFFBFFLRL
        ///FFFFFBBRLR
        ///BFFBFBBLLR
        ///FFBBBBBLRR
        ///FBBFFBBLLR
        ///FFFFFBBLLR
        ///FBBFFFBRLR
        ///FFBFBBFRRR
        ///FBBFFFFLRL
        ///FFBFBBFLLR
        ///BFBBBBFRRL
        ///FFFFBBBLLR
        ///FFBFFFFRLL
        ///FFBBFFBLRL
        ///BBFFFBBRLR
        ///FBBFBBFRLL
        ///FBBBFBFRRR
        ///FBBBBBBRLR
        ///BFBBFBBRRL
        ///FBBBBFFRLR
        ///FBFBFBBLLL
        ///FBBFFFBLRL
        ///BFFBBBFRLL
        ///FFBFFBBLLL
        ///FFFFFFBRLL
        ///BFFBFBFRLR
        ///FBBFBBBRRL
        ///BFBFBFFL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05Input {
            get {
                return ResourceManager.GetString("Day05Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adgvrhblps
        ///pghsdrbmalv
        ///hrlbpdasgv
        ///bgvsdplahr
        ///
        ///lgnpfhrm
        ///hwmng
        ///gunhmo
        ///
        ///txkeafsbgjuizd
        ///etmcgdbfajuz
        ///
        ///xdtzjioqavmchsbfrkp
        ///bzjkriqmvxedotpcf
        ///azjckxmqovtidbprf
        ///fcxmevrkojzpdibqt
        ///roifztvxmbpwcndkjq
        ///
        ///ylcixrdoejn
        ///dyoejlrcxin
        ///dnorleijxyc
        ///
        ///u
        ///u
        ///
        ///nfjrt
        ///hvgqxculeszok
        ///pmwryfdiab
        ///
        ///gh
        ///ebzkr
        ///byqusikr
        ///
        ///b
        ///b
        ///alyr
        ///t
        ///
        ///jzbafspmynwgqdeuklxc
        ///anbkgduyexjlzmpcfwq
        ///zxdkiujqeglcfynwpamb
        ///qwcubamjpxyngkdlzfe
        ///upadgfkywmnxeqbhjzcl
        ///
        ///g
        ///l
        ///g
        ///g
        ///pg
        ///
        ///mazi
        ///mnzdai
        ///zmia
        ///izma
        ///
        ///pqzl
        ///pzql
        ///zvciplq
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to striped tan bags contain 2 light silver bags, 1 drab black bag, 2 clear tan bags, 2 mirrored tan bags.
        ///dark black bags contain 1 vibrant indigo bag, 5 muted gold bags, 4 bright tomato bags, 3 dull tan bags.
        ///dim silver bags contain 1 vibrant black bag, 3 muted cyan bags, 4 plaid turquoise bags, 4 faded orange bags.
        ///faded maroon bags contain 3 pale aqua bags.
        ///dim crimson bags contain 1 faded orange bag, 2 plaid silver bags.
        ///plaid indigo bags contain 1 dull purple bag, 2 plaid cyan bags, 4 mirrored gold b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07Input {
            get {
                return ResourceManager.GetString("Day07Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acc -7
        ///acc +6
        ///acc +4
        ///nop +191
        ///jmp +199
        ///acc +44
        ///acc -9
        ///jmp +505
        ///acc -12
        ///acc +45
        ///jmp +204
        ///jmp +129
        ///acc +17
        ///nop +287
        ///jmp +584
        ///acc +16
        ///jmp +363
        ///acc +4
        ///nop +142
        ///acc +34
        ///nop +345
        ///jmp +522
        ///jmp +53
        ///acc -10
        ///jmp +524
        ///jmp +492
        ///jmp +319
        ///acc -9
        ///jmp +550
        ///acc -19
        ///jmp +15
        ///acc +24
        ///jmp +30
        ///acc -19
        ///acc +12
        ///acc -2
        ///jmp +274
        ///nop +91
        ///acc +10
        ///acc +4
        ///jmp +501
        ///acc +49
        ///acc +29
        ///jmp +488
        ///jmp +504
        ///jmp +277
        ///acc +20
        ///acc +34
        ///jmp -40
        ///acc +10
        ///acc -4
        ///acc -19
        ///acc +38
        ///jmp +239
        ///acc -16
        ///acc - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08Input {
            get {
                return ResourceManager.GetString("Day08Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///17
        ///32
        ///2
        ///19
        ///45
        ///22
        ///18
        ///38
        ///8
        ///16
        ///13
        ///41
        ///35
        ///23
        ///29
        ///11
        ///46
        ///12
        ///27
        ///49
        ///34
        ///20
        ///14
        ///47
        ///50
        ///10
        ///15
        ///17
        ///21
        ///57
        ///25
        ///19
        ///18
        ///22
        ///76
        ///24
        ///32
        ///26
        ///28
        ///23
        ///30
        ///29
        ///31
        ///33
        ///27
        ///35
        ///42
        ///34
        ///36
        ///91
        ///40
        ///37
        ///38
        ///43
        ///47
        ///44
        ///41
        ///45
        ///72
        ///49
        ///61
        ///80
        ///55
        ///66
        ///71
        ///56
        ///117
        ///141
        ///69
        ///135
        ///70
        ///73
        ///83
        ///74
        ///75
        ///114
        ///78
        ///79
        ///113
        ///213
        ///189
        ///86
        ///104
        ///173
        ///105
        ///116
        ///131
        ///152
        ///194
        ///149
        ///125
        ///139
        ///142
        ///143
        ///144
        ///247
        ///188
        ///157
        ///191
        ///153
        ///238
        ///164
        ///165
        ///190
        ///202
        ///209
        ///211
        ///393
        ///269
        ///221
        ///291
        ///299
        ///281
        ///264
        ///267
        ///268
        ///327
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day09Input {
            get {
                return ResourceManager.GetString("Day09Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLLLL.LLLL.LL..LLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLLLLLLLLL.L.LLLLLLLLL.LLLLLLL.LLLL.LLLLLLLL
        ///LLLLLLLL.LLLLL.LLLLLLLLLLLLLLLL.LLLLLLLL.LLLLLLLLLLLL.LLLLLLLLLLLLLLL.LL.LLL.LLLL.LLLLLLLL
        ///LLLLLLLLL.LLLLLLLLLLLLLLLLLLLLL.LLLLLLL..LLLLLL.LLLLLLLLLL..LLLLLLLL.LLLLLLLLL.LLLLLLLLLLL
        ///LLLLL.LLLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLL..LLLLL.LLLLL.LLLLLLLLLLLLLLL.L.LLLLLLLLL.LLL.LLLL
        ///LLLLL.LLL.L..L.LLLLL.LLL.LLLLLLLLLLLLLLL.LL.LLLLLLL.L.LLL..LLLLLLLLL.LLLLLLL.LLLL.LLLLLLLL
        ///LLLLL.LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLL.LLLLLL.LLLL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11Input {
            get {
                return ResourceManager.GetString("Day11Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R90
        ///N2
        ///N2
        ///F94
        ///R90
        ///E3
        ///F2
        ///L90
        ///L90
        ///F66
        ///S5
        ///L90
        ///W3
        ///R90
        ///N3
        ///W2
        ///N2
        ///W1
        ///R90
        ///E3
        ///F100
        ///S4
        ///F66
        ///R180
        ///F96
        ///R90
        ///N2
        ///R90
        ///E2
        ///S3
        ///E1
        ///F65
        ///W4
        ///F6
        ///L180
        ///W2
        ///L90
        ///F95
        ///L90
        ///F97
        ///E2
        ///F36
        ///E2
        ///R90
        ///E4
        ///F98
        ///N4
        ///F70
        ///S1
        ///R270
        ///E1
        ///F13
        ///R90
        ///W1
        ///L90
        ///F82
        ///S2
        ///R90
        ///N2
        ///F80
        ///N1
        ///R90
        ///F26
        ///W4
        ///F23
        ///S5
        ///F72
        ///N5
        ///W2
        ///N5
        ///F47
        ///L270
        ///F18
        ///W1
        ///L90
        ///F91
        ///R90
        ///W5
        ///N2
        ///F60
        ///E5
        ///S3
        ///R90
        ///R180
        ///S3
        ///L90
        ///W4
        ///F80
        ///S2
        ///L90
        ///F31
        ///W1
        ///L90
        ///F45
        ///S3
        ///F64
        ///N1
        ///W4
        ///N2
        ///R180
        ///W3
        ///R90
        ///S1
        ///F7
        ///W1
        ///R180
        ///W1
        ///S4
        ///E4
        ///W4
        ///F87
        ///R90        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day12Input {
            get {
                return ResourceManager.GetString("Day12Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask = 010X1100101X00X01001X11010X111100X01
        ///mem[23014] = 9778
        ///mem[42882] = 140716
        ///mem[65461] = 458355100
        ///mem[60151] = 31172
        ///mem[47143] = 7055
        ///mask = X101XX001XX1001010X101X1101011100101
        ///mem[26134] = 4394
        ///mem[18808] = 352500
        ///mem[18556] = 87307674
        ///mask = X11X110X1011X11X0001011000000X110000
        ///mem[49018] = 14063312
        ///mem[42211] = 45834020
        ///mem[36848] = 5772919
        ///mask = X1X1110110100001100X000100111X001X01
        ///mem[9118] = 531662307
        ///mem[31896] = 259680444
        ///mem[35532] = 125291736
        ///mem[1284] = 696970
        ///mask =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day14Input {
            get {
                return ResourceManager.GetString("Day14Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departure location: 29-766 or 786-950
        ///departure station: 40-480 or 491-949
        ///departure platform: 46-373 or 397-957
        ///departure track: 33-657 or 673-970
        ///departure date: 31-433 or 445-961
        ///departure time: 33-231 or 250-966
        ///arrival location: 48-533 or 556-974
        ///arrival station: 42-597 or 620-957
        ///arrival platform: 32-119 or 140-967
        ///arrival track: 28-750 or 762-973
        ///class: 26-88 or 101-950
        ///duration: 30-271 or 293-974
        ///price: 33-712 or 718-966
        ///route: 49-153 or 159-953
        ///row: 36-842 or 851-972
        ///seat: 43-181 or  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day16Input {
            get {
                return ResourceManager.GetString("Day16Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 + (9 * 8 + 5 + 5 * (3 * 4 * 7 + 6 * 4)) * ((3 * 6 + 3 * 4 * 7 * 4) + 4 * 3 * 5 + 5 * (5 * 6 + 7)) * 2 + 6 * 4
        ///9 * 4 * ((9 * 8 + 9 + 2 + 9) + 2 * 9 + 2 + 2) * 5 * 6
        ///3 * ((9 * 3 * 8 * 6 * 6 * 7) + 8) * 2 * 9 + 4 * 8
        ///(3 + 4 + 4 * 4 + 9) + (7 + 6 + 2 * 8) * 9 + 7 * 8
        ///9 + 6 + 6 + 9 * 9 * 5
        ///(3 * 5 + (4 + 3 * 7 * 8) + 7 + 8 + 2) * 8 * (3 * 4 * 8) * ((4 + 5 * 2) * 7)
        ///6 + (5 + 8 * (6 * 8 * 9 + 9 + 8 * 9) * 4 + (5 * 9)) * 2 + 2
        ///(6 + 8 + (6 * 6 + 2) * 6 * (7 + 7 + 8 + 9)) * 3 + 8 + (6 * (8 + 8 + 9)) + 2
        ///9 +  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day18Input {
            get {
                return ResourceManager.GetString("Day18Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97: 138 57 | 12 83
        ///131: 20 83 | 74 57
        ///7: 57 110 | 83 51
        ///48: 17 83 | 56 57
        ///2: 83 57
        ///40: 57 101 | 83 93
        ///16: 12 83 | 47 57
        ///42: 15 83 | 66 57
        ///62: 83 134 | 57 18
        ///55: 124 57 | 45 83
        ///1: 57 116 | 83 93
        ///63: 83 1 | 57 32
        ///83: &quot;a&quot;
        ///72: 57 83 | 83 83
        ///18: 83 57 | 57 83
        ///67: 90 83 | 99 57
        ///91: 83 108 | 57 72
        ///8: 42
        ///116: 83 18 | 57 72
        ///41: 57 83
        ///130: 57 84 | 83 50
        ///26: 57 12 | 83 124
        ///103: 134 57 | 45 83
        ///39: 83 18 | 57 138
        ///46: 83 47 | 57 138
        ///129: 57 138 | 83 108
        ///58: 108 57 | 72 83
        ///138: 57 57 | 83 57
        ///49 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day19Input {
            get {
                return ResourceManager.GetString("Day19Input", resourceCulture);
            }
        }
    }
}
