//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-5 l: fllxf
        ///4-5 r: rrrjmrrrrrrh
        ///1-4 k: kkksk
        ///7-8 k: tknsqknzkckrwkjkk
        ///2-3 p: mpbstpxmsxmpnhbwlb
        ///2-7 j: xkjjtjjjj
        ///2-7 m: gczbmgk
        ///15-16 q: qqqqqqqqqckqqqfqqq
        ///7-14 d: dgdddlddddddrvfddnsd
        ///7-12 r: rrrrrrrrbrrrl
        ///2-11 p: zppjpwpqppbnppd
        ///6-8 w: wqhwwnpwwwr
        ///4-10 m: fmkmrrrdkmr
        ///1-2 n: nnjvtnzk
        ///3-8 t: tdxmzslxtvft
        ///13-14 m: mmmmmhmmmmmmmm
        ///9-10 l: lljllllllll
        ///12-16 t: vdtbdtxtttttrctttkt
        ///2-6 q: nqghxqgjqvzswbxww
        ///4-6 k: khkkkkvrkgfwvbd
        ///4-5 r: hrrpv
        ///5-8 g: gggggggg
        ///5-8 f: fjsfftfs
        ///9-12 p: ppfpnxpv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Input {
            get {
                return ResourceManager.GetString("Day02Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......##....#...#..#.#....#....
        ///.......#...#..#..#....##.......
        ///#.#...#........###.#.##..#.....
        ///.......#.....##.#..##...##.##..
        ///.#...#.#...##..........#..#....
        ///#.......##.....###.#...#......#
        ///.........#....#.#.......#..#...
        ///..#.......####.......###..##...
        ///.#.#.##..#.#...##..#...###...##
        ///...................#...........
        ///....#.#.......#..........#.#..#
        ///..#.#...........####.#.......#.
        ///.....#.##..#..##..#.#...#......
        ///#.##...###..#................##
        ///...#...#...#..##.#............#
        ///#.##....##....#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Input {
            get {
                return ResourceManager.GetString("Day03Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:2033
        ///hgt:177cm pid:173cm
        ///ecl:utc byr:2029 hcl:#efcc98 iyr:2023
        ///
        ///pid:337605855 cid:249 byr:1952 hgt:155cm
        ///ecl:grn iyr:2017 eyr:2026 hcl:#866857
        ///
        ///cid:242 iyr:2011 pid:953198122 eyr:2029 ecl:blu hcl:#888785
        ///
        ///hgt:173cm hcl:#341e13
        ///cid:341
        ///pid:112086592
        ///iyr:2012 byr:2011 ecl:amb
        ///eyr:2030
        ///
        ///pid:790332032
        ///iyr:2019
        ///eyr:2023 byr:1969 ecl:brn
        ///hgt:163cm
        ///hcl:#623a2f
        ///
        ///byr:1920 eyr:2023 cid:146 pid:890112986 hgt:171cm hcl:#b6652a iyr:2017 ecl:hzl
        ///
        ///hcl:#c0946f byr:1967 cid:199 ecl:gry
        ///iyr:2012 p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Input {
            get {
                return ResourceManager.GetString("Day04Input", resourceCulture);
            }
        }
    }
}
