//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-5 l: fllxf
        ///4-5 r: rrrjmrrrrrrh
        ///1-4 k: kkksk
        ///7-8 k: tknsqknzkckrwkjkk
        ///2-3 p: mpbstpxmsxmpnhbwlb
        ///2-7 j: xkjjtjjjj
        ///2-7 m: gczbmgk
        ///15-16 q: qqqqqqqqqckqqqfqqq
        ///7-14 d: dgdddlddddddrvfddnsd
        ///7-12 r: rrrrrrrrbrrrl
        ///2-11 p: zppjpwpqppbnppd
        ///6-8 w: wqhwwnpwwwr
        ///4-10 m: fmkmrrrdkmr
        ///1-2 n: nnjvtnzk
        ///3-8 t: tdxmzslxtvft
        ///13-14 m: mmmmmhmmmmmmmm
        ///9-10 l: lljllllllll
        ///12-16 t: vdtbdtxtttttrctttkt
        ///2-6 q: nqghxqgjqvzswbxww
        ///4-6 k: khkkkkvrkgfwvbd
        ///4-5 r: hrrpv
        ///5-8 g: gggggggg
        ///5-8 f: fjsfftfs
        ///9-12 p: ppfpnxpv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Input {
            get {
                return ResourceManager.GetString("Day02Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......##....#...#..#.#....#....
        ///.......#...#..#..#....##.......
        ///#.#...#........###.#.##..#.....
        ///.......#.....##.#..##...##.##..
        ///.#...#.#...##..........#..#....
        ///#.......##.....###.#...#......#
        ///.........#....#.#.......#..#...
        ///..#.......####.......###..##...
        ///.#.#.##..#.#...##..#...###...##
        ///...................#...........
        ///....#.#.......#..........#.#..#
        ///..#.#...........####.#.......#.
        ///.....#.##..#..##..#.#...#......
        ///#.##...###..#................##
        ///...#...#...#..##.#............#
        ///#.##....##....#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Input {
            get {
                return ResourceManager.GetString("Day03Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:2033
        ///hgt:177cm pid:173cm
        ///ecl:utc byr:2029 hcl:#efcc98 iyr:2023
        ///
        ///pid:337605855 cid:249 byr:1952 hgt:155cm
        ///ecl:grn iyr:2017 eyr:2026 hcl:#866857
        ///
        ///cid:242 iyr:2011 pid:953198122 eyr:2029 ecl:blu hcl:#888785
        ///
        ///hgt:173cm hcl:#341e13
        ///cid:341
        ///pid:112086592
        ///iyr:2012 byr:2011 ecl:amb
        ///eyr:2030
        ///
        ///pid:790332032
        ///iyr:2019
        ///eyr:2023 byr:1969 ecl:brn
        ///hgt:163cm
        ///hcl:#623a2f
        ///
        ///byr:1920 eyr:2023 cid:146 pid:890112986 hgt:171cm hcl:#b6652a iyr:2017 ecl:hzl
        ///
        ///hcl:#c0946f byr:1967 cid:199 ecl:gry
        ///iyr:2012 p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Input {
            get {
                return ResourceManager.GetString("Day04Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFFFBFBLLR
        ///BFBFFBBLLR
        ///BBFFFFBLRR
        ///FBFBFFFRLL
        ///BFFBFFFRRR
        ///BFBFBFFRLR
        ///FFFBBBBLRL
        ///BFFFFBFLLL
        ///FFFFBBFLLR
        ///BBFFBFFRRR
        ///FBBFBBFLRL
        ///BFBFFBFLRR
        ///FBFFBFFLLL
        ///FFFBFFFRLR
        ///FFFBFBBLLR
        ///BBFFBFFLRL
        ///FFFFFBBRLR
        ///BFFBFBBLLR
        ///FFBBBBBLRR
        ///FBBFFBBLLR
        ///FFFFFBBLLR
        ///FBBFFFBRLR
        ///FFBFBBFRRR
        ///FBBFFFFLRL
        ///FFBFBBFLLR
        ///BFBBBBFRRL
        ///FFFFBBBLLR
        ///FFBFFFFRLL
        ///FFBBFFBLRL
        ///BBFFFBBRLR
        ///FBBFBBFRLL
        ///FBBBFBFRRR
        ///FBBBBBBRLR
        ///BFBBFBBRRL
        ///FBBBBFFRLR
        ///FBFBFBBLLL
        ///FBBFFFBLRL
        ///BFFBBBFRLL
        ///FFBFFBBLLL
        ///FFFFFFBRLL
        ///BFFBFBFRLR
        ///FBBFBBBRRL
        ///BFBFBFFL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05Input {
            get {
                return ResourceManager.GetString("Day05Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adgvrhblps
        ///pghsdrbmalv
        ///hrlbpdasgv
        ///bgvsdplahr
        ///
        ///lgnpfhrm
        ///hwmng
        ///gunhmo
        ///
        ///txkeafsbgjuizd
        ///etmcgdbfajuz
        ///
        ///xdtzjioqavmchsbfrkp
        ///bzjkriqmvxedotpcf
        ///azjckxmqovtidbprf
        ///fcxmevrkojzpdibqt
        ///roifztvxmbpwcndkjq
        ///
        ///ylcixrdoejn
        ///dyoejlrcxin
        ///dnorleijxyc
        ///
        ///u
        ///u
        ///
        ///nfjrt
        ///hvgqxculeszok
        ///pmwryfdiab
        ///
        ///gh
        ///ebzkr
        ///byqusikr
        ///
        ///b
        ///b
        ///alyr
        ///t
        ///
        ///jzbafspmynwgqdeuklxc
        ///anbkgduyexjlzmpcfwq
        ///zxdkiujqeglcfynwpamb
        ///qwcubamjpxyngkdlzfe
        ///upadgfkywmnxeqbhjzcl
        ///
        ///g
        ///l
        ///g
        ///g
        ///pg
        ///
        ///mazi
        ///mnzdai
        ///zmia
        ///izma
        ///
        ///pqzl
        ///pzql
        ///zvciplq
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to striped tan bags contain 2 light silver bags, 1 drab black bag, 2 clear tan bags, 2 mirrored tan bags.
        ///dark black bags contain 1 vibrant indigo bag, 5 muted gold bags, 4 bright tomato bags, 3 dull tan bags.
        ///dim silver bags contain 1 vibrant black bag, 3 muted cyan bags, 4 plaid turquoise bags, 4 faded orange bags.
        ///faded maroon bags contain 3 pale aqua bags.
        ///dim crimson bags contain 1 faded orange bag, 2 plaid silver bags.
        ///plaid indigo bags contain 1 dull purple bag, 2 plaid cyan bags, 4 mirrored gold b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07Input {
            get {
                return ResourceManager.GetString("Day07Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acc -7
        ///acc +6
        ///acc +4
        ///nop +191
        ///jmp +199
        ///acc +44
        ///acc -9
        ///jmp +505
        ///acc -12
        ///acc +45
        ///jmp +204
        ///jmp +129
        ///acc +17
        ///nop +287
        ///jmp +584
        ///acc +16
        ///jmp +363
        ///acc +4
        ///nop +142
        ///acc +34
        ///nop +345
        ///jmp +522
        ///jmp +53
        ///acc -10
        ///jmp +524
        ///jmp +492
        ///jmp +319
        ///acc -9
        ///jmp +550
        ///acc -19
        ///jmp +15
        ///acc +24
        ///jmp +30
        ///acc -19
        ///acc +12
        ///acc -2
        ///jmp +274
        ///nop +91
        ///acc +10
        ///acc +4
        ///jmp +501
        ///acc +49
        ///acc +29
        ///jmp +488
        ///jmp +504
        ///jmp +277
        ///acc +20
        ///acc +34
        ///jmp -40
        ///acc +10
        ///acc -4
        ///acc -19
        ///acc +38
        ///jmp +239
        ///acc -16
        ///acc - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08Input {
            get {
                return ResourceManager.GetString("Day08Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///17
        ///32
        ///2
        ///19
        ///45
        ///22
        ///18
        ///38
        ///8
        ///16
        ///13
        ///41
        ///35
        ///23
        ///29
        ///11
        ///46
        ///12
        ///27
        ///49
        ///34
        ///20
        ///14
        ///47
        ///50
        ///10
        ///15
        ///17
        ///21
        ///57
        ///25
        ///19
        ///18
        ///22
        ///76
        ///24
        ///32
        ///26
        ///28
        ///23
        ///30
        ///29
        ///31
        ///33
        ///27
        ///35
        ///42
        ///34
        ///36
        ///91
        ///40
        ///37
        ///38
        ///43
        ///47
        ///44
        ///41
        ///45
        ///72
        ///49
        ///61
        ///80
        ///55
        ///66
        ///71
        ///56
        ///117
        ///141
        ///69
        ///135
        ///70
        ///73
        ///83
        ///74
        ///75
        ///114
        ///78
        ///79
        ///113
        ///213
        ///189
        ///86
        ///104
        ///173
        ///105
        ///116
        ///131
        ///152
        ///194
        ///149
        ///125
        ///139
        ///142
        ///143
        ///144
        ///247
        ///188
        ///157
        ///191
        ///153
        ///238
        ///164
        ///165
        ///190
        ///202
        ///209
        ///211
        ///393
        ///269
        ///221
        ///291
        ///299
        ///281
        ///264
        ///267
        ///268
        ///327
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day09Input {
            get {
                return ResourceManager.GetString("Day09Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLLLL.LLLL.LL..LLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLLLLLLLLL.L.LLLLLLLLL.LLLLLLL.LLLL.LLLLLLLL
        ///LLLLLLLL.LLLLL.LLLLLLLLLLLLLLLL.LLLLLLLL.LLLLLLLLLLLL.LLLLLLLLLLLLLLL.LL.LLL.LLLL.LLLLLLLL
        ///LLLLLLLLL.LLLLLLLLLLLLLLLLLLLLL.LLLLLLL..LLLLLL.LLLLLLLLLL..LLLLLLLL.LLLLLLLLL.LLLLLLLLLLL
        ///LLLLL.LLLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLL..LLLLL.LLLLL.LLLLLLLLLLLLLLL.L.LLLLLLLLL.LLL.LLLL
        ///LLLLL.LLL.L..L.LLLLL.LLL.LLLLLLLLLLLLLLL.LL.LLLLLLL.L.LLL..LLLLLLLLL.LLLLLLL.LLLL.LLLLLLLL
        ///LLLLL.LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLL.LLLLLL.LLLL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11Input {
            get {
                return ResourceManager.GetString("Day11Input", resourceCulture);
            }
        }
    }
}
